#!/usr/bin/env bash

set -eu

$HOME/dotfiles/init/install_shell
$HOME/dotfiles/init/install_apps
$HOME/dotfiles/init/install_nvm
$HOME/dotfiles/init/install_fonts

printf "\n\nInstall Complete\nStart a new terminal for all changes to take effect"