#!/usr/bin/env bash


# This might come after brew is installed but before a new terminal
if [ "$(uname)" = "Darwin" ]; then
    # TODO: check that this is correct for MAC
    eval "\$(${HOMEBREW_PREFIX}/bin/brew shellenv)"
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

if [ ! -f "$NVM_DIR/nvm.sh" ]; then
    echo "Installing nvm"
    PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash'
    zsh -lic "nvm install 20" # node 12
    zsh -lic "nvm use 20"
    zsh -lic "nvm alias default 20"
fi

# Install pnpm
brew install pnpm