#!/usr/bin/env bash

# does not work on WSL

if [ ! -f /proc/sys/fs/binfmt_misc/WSLInterop ]; then
  exit
fi

brew install font-hack-nerd-font
brew install font-meslo-lg-nerd-font
brew install --cask font-fira-code-nerd-font