#!/bin/bash

# Run with
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/kyeotic/dotfiles/refs/heads/main/init/install)"

set -u

if [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
    # linux or wsl
    sudo apt install build-essential
fi

cd $HOME
git clone https://github.com/kyeotic/dotfiles.git

cd dotfiles
./init/init