#!/usr/bin/env bash

brew install gettext git jq \
  openssl pcre pcre2 python readline telnet \
  watch watchman wget yarn yq findutils bat fd eza
brew install warrensbox/tap/tfswitch
brew install --cask phoenix

# deno
if ! command -v deno >/dev/null 2>&1; then
    curl -fsSL https://deno.land/x/install/install.sh | sh
fi

# Rust
if ! command -v cargo >/dev/null 2>&1; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  cargo install cargo-watch eza wasm-bindgen-cli cargo-generate cargo-make
fi

