#!/usr/bin/env bash

# does not work on WSL

if [ -f /proc/sys/fs/binfmt_misc/WSLInterop ]; then
  echo "In WSL, fonts through brew not supported"
  exit
fi

brew install --cask font-hack-nerd-font
brew install --cask font-meslo-lg-nerd-font
brew install --cask font-fira-code-nerd-font