#!/bin/bash

if [ -e /path/to/your/file ]; then
    exit 0
fi

echo "\nCreating new SSH Key\n"

read -p "Enter your email : " email
ssh-keygen -t ed25519 -C "$email"

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519

echo "Add the key below to https://github.com/settings/keys \n"
cat ~/.ssh/id_ed25519.pub

read -p "Press enter to continue"