#!/bin/bash

if [ -e ~/.ssh/id_ed25519 ]; then
    exit 0
fi

# Set email based on username
if [ "$(whoami)" = "tkye" ]; then
    email="tkye@squareup.com"
else
    email="tim@kye.dev"
fi

printf "\nCreating new SSH Key ($email)\n"

ssh-keygen -t ed25519 -C "$email"

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519

printf "Add the key below to https://github.com/settings/keys \n"
cat ~/.ssh/id_ed25519.pub

read -p "Press enter to continue"
