#!/usr/bin/env bash

# ----------------------
# Prerequisites
#
# Homebrew must already be installed
# The init script will handle this, do not run this directly
# ----------------------


# Install fish
brew install fish
chsh -s /usr/local/bin/fish

# Install and configure oh my fish
curl -L https://get.oh-my.fish | fish

# Install theme
omf install bobthefish 

# install fisher
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
fisher install jhillyerd/plugin-git

# run the config linker
$HOME/dotfiles/link