#!/usr/bin/env bash

# does not work on WSL

if uname -r |grep -q 'Microsoft' ; then
  exit
fi

brew tap homebrew/cask-fonts
brew install font-hack-nerd-font
brew install font-meslo-lg-nerd-font
# brew install --cask font-fira-code
brew install --cask font-fira-code-nerd-font