conky.config = {
    alignment = 'top_right',
    gap_x = 5,
    gap_y = 5,
    xinerama_head = 1,
    background = false,
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'Fira Code:size=12',
    minimum_height = 5,
    minimum_width = 400,
    no_buffers = true,
    out_to_x = true,
    own_window = true,
    own_window_class = 'conky',
    own_window_type = 'normal',
    own_window_transparent = true,
    own_window_colour = '#000000',
    own_window_argb_visual = true,
    own_window_argb_value = 200,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    update_interval = 1.0,
    uppercase = false,
    use_xft = true,
    short_units = true,
}

conky.text = [[
${color grey}RAM:$color $memperc%${goto 140}${color grey}CPU:$color $cpu%${goto 240}${color grey}GPU:$color ${texeci 2 nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits}%${goto 360}${color grey}vRAM:$color ${texeci 2 USED=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits); TOTAL=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits); echo $((USED * 100 / TOTAL))}%
${color grey}${mem} | ${memmax}${goto 174}$color${texeci 2 cat /sys/class/thermal/thermal_zone0/temp | head -c 2}°C${goto 284}${texeci 2 nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits}°C
]]